#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

name: AR

run-name: ${{ (github.event_name == 'pull_request' && github.event.pull_request.title || format('AR - {0}', github.ref_name)) }}

on:
  pull_request:
  workflow_dispatch:
    inputs:
        CLEAN_ARTIFACTS:
            type: boolean
            description: Use no artifacts for next build (will be saved as clean artifacts)
            required: false
            default: false
        windows_build:
            description: 'Build Windows'
            required: false
            default: true
            type: boolean
        linux_build:
            description: 'Build Linux'
            required: false
            default: true
            type: boolean
        android_build:
            description: 'Build Android'
            required: false
            default: true
            type: boolean
  push:
    branches:
      - main
      - development
      - stabilization/**
      - hotfix/**

jobs:

# The following jobs are used to build the project for the different platforms.
# The parameters are the following:
# - compiler: The compiler to use (msvc, clang, gcc)
# - config: The configuration to use (profile, release). This is defined by presets in ../scripts/build/Platform/<os>/build_config.json
# - image: The image to use (windows-2022, ubuntu-22.04). The images are defined from runners images repo: https://github.com/actions/runner-images
# - platform: The platform to use (Windows, Linux, Android)
# - type: The type of build to use (profile, asset_profile, test_profile, test_cpu_profile, release)
# - last_artifact: Whether to use the artifact from the last run, from the target branch if it's a pull request or its own branch if it's a push
# - desktop: Whether to use the desktop environment for tests (Linux only)
# - msvc_toolset_version: MSVC toolset version to install (Windows only)
# - msvc_platform_toolset: MSVC platform toolset name, e.g. v143 (Windows only)
# - clang_version: Clang major version to install (Linux only)
# - ndk_version: Android NDK version to install (Android only)
# - cmake_version: CMake version constraint to use (all platforms)
# - gradle_version: Gradle version to use (Android only)

#### Windows Build ####
    Windows-Profile:
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.windows_build }}
        uses: ./.github/workflows/windows-build.yml
        with:
            compiler: msvc
            config: profile
            image: windows-2022
            platform: Windows
            type: profile
            last_artifact: ${{ inputs.CLEAN_ARTIFACTS == false }} # If CLEAN_ARTIFACTS is false, then this returns true
            msvc_toolset_version: '14.29'
            msvc_platform_toolset: 'v142'
            cmake_version: '~3.24'
    
    Windows-Asset:
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.windows_build }}
        needs: Windows-Profile
        uses: ./.github/workflows/windows-build.yml
        with:
            compiler: msvc
            config: profile
            image: windows-2022
            platform: Windows
            type: asset_profile
            msvc_toolset_version: '14.29'
            msvc_platform_toolset: 'v142'
            cmake_version: '~3.24'

    Windows-Test:
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.windows_build }}
        needs: Windows-Asset
        uses: ./.github/workflows/windows-build.yml
        with:
            compiler: msvc
            config: profile
            image: windows-2022
            platform: Windows
            type: test_cpu_profile
            msvc_toolset_version: '14.29'
            msvc_platform_toolset: 'v142'
            cmake_version: '~3.24'

    Windows-Release:
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.windows_build }}
        uses: ./.github/workflows/windows-build.yml
        with:
            compiler: msvc
            config: release
            image: windows-2022
            platform: Windows
            type: release
            last_artifact: ${{ inputs.CLEAN_ARTIFACTS == false }}
            msvc_toolset_version: '14.29'
            msvc_platform_toolset: 'v142'
            cmake_version: '~3.24'

#### Linux Build ####
    Linux-Profile:
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.linux_build }}
        uses: ./.github/workflows/linux-build.yml
        with:
            compiler: clang
            config: profile
            image: ubuntu-22.04
            platform: Linux
            type: profile
            last_artifact: ${{ inputs.CLEAN_ARTIFACTS == false }}
            clang_version: '14'
            cmake_version: '~3.24'

    Linux-Asset:
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.linux_build }}
        needs: Linux-Profile
        uses: ./.github/workflows/linux-build.yml
        with:
            compiler: clang
            config: profile
            image: ubuntu-22.04
            platform: Linux
            type: asset_profile
            clang_version: '14'
            cmake_version: '~3.24'

    Linux-Test:
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.linux_build }}
        needs: Linux-Asset
        uses: ./.github/workflows/linux-build.yml
        with:
            compiler: clang
            config: profile
            image: ubuntu-22.04
            platform: Linux
            type: test_profile
            desktop: true
            clang_version: '14'
            cmake_version: '~3.24'

#### Android Build ####
    Android-Profile:
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.android_build }}
        uses: ./.github/workflows/android-build.yml
        with:
            compiler: clang
            config: profile
            image: windows-2022
            platform: Android
            type: profile
            last_artifact: ${{ inputs.CLEAN_ARTIFACTS == false }}
            ndk_version: '25.1.8937393'
            gradle_version: '8.12'
            cmake_version: '~3.24'

    Android-Asset:
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.android_build }}
        uses: ./.github/workflows/android-build.yml
        with:
            compiler: msvc
            config: asset_profile
            image: windows-2022
            platform: Android
            type: asset_profile
            last_artifact: ${{ inputs.CLEAN_ARTIFACTS == false }}
            msvc_toolset_version: '14.29'
            msvc_platform_toolset: 'v142'
            ndk_version: '25.1.8937393'
            gradle_version: '8.12'
            cmake_version: '~3.24'
            
    Android-Gradle:
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.android_build }}
        uses: ./.github/workflows/android-build.yml
        with:
            compiler: clang
            config: gradle
            image: windows-2022
            platform: Android
            type: gradle
            last_artifact: ${{ inputs.CLEAN_ARTIFACTS == false }}
            ndk_version: '25.1.8937393'
            gradle_version: '8.12'
            cmake_version: '~3.24'
